name: Deploy to Tencent COS

# 当推送到 main 分支时触发
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1. 检出代码
    - name: Checkout
      uses: actions/checkout@v4
    
    # 2. 安装和配置 coscmd 工具
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install coscmd
      run: |
        pip install coscmd
    
    # 3. 配置 coscmd
    - name: Configure coscmd
      run: |
        coscmd config -a ${{ secrets.TENCENT_SECRET_ID }} \
                     -s ${{ secrets.TENCENT_SECRET_KEY }} \
                     -b ${{ secrets.COS_BUCKET }} \
                     -r ${{ secrets.COS_REGION }}
    
    # 4. 同步文件到 COS
    - name: Upload to COS
      run: |
        # 上传所有文件到 COS，删除远程多余文件
        coscmd upload -r -s --delete ./ /
        
        # 设置 index.html 的正确 Content-Type 和 Content-Disposition
        coscmd putobjectacl --grant-read "*" index.html || true
    
    # 5. 设置文件的正确 Headers（解决下载问题）
    - name: Set file headers
      run: |
        # 为 HTML 文件设置正确的 Content-Type
        find . -name "*.html" -type f | while read file; do
          filename=$(basename "$file")
          echo "Setting headers for $filename"
          # 注意：coscmd 可能不支持直接设置 headers，这里主要是确保权限正确
          coscmd putobjectacl --grant-read "*" "$filename" || true
        done
    
    # 6. 输出部署结果
    - name: Deploy Success
      run: |
        echo "🎉 部署成功!"
        echo "网站地址: https://${{ secrets.COS_BUCKET }}.cos-website.${{ secrets.COS_REGION }}.myqcloud.com"
