name: Deploy to Tencent COS

# 当推送到 main 分支时触发
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1. 检出代码
    - name: Checkout
      uses: actions/checkout@v4
    
    # 2. 设置 Python 环境
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    # 3. 安装 COSCMD
    - name: Install coscmd
      run: |
        pip install coscmd
        echo "COSCMD installed successfully"
    
    # 4. 配置 COSCMD
    - name: Configure coscmd
      run: |
        coscmd config -a ${{ secrets.TENCENT_SECRET_ID }} \
                     -s ${{ secrets.TENCENT_SECRET_KEY }} \
                     -b ${{ secrets.COS_BUCKET }} \
                     -r ${{ secrets.COS_REGION }}
        echo "COSCMD configured successfully"
    
    # 5. 上传所有静态文件并设置公有读权限
    - name: Upload all static files with public-read permissions
      run: |
        echo "Uploading all static files with public-read permissions..."
        
        # 上传所有静态网站文件，设置公有读权限，并排除不需要的文件
        coscmd upload -rs -f -H "{'x-cos-acl':'public-read'}" ./ / \
          --ignore ".git/*,.github/*,node_modules/*,.DS_Store,*.md,README*,LICENSE*,*.yml,*.yaml,.env*,*.zip,*.tar,*.gz,package*.json,tsconfig.json,webpack.config.js,gulpfile.js,Gruntfile.js,.gitignore,.gitattributes,.editorconfig,.eslintrc*,.prettierrc*,*.log"
        
        echo "✅ All static files uploaded with public-read permissions"
        echo "📁 Supported file types: HTML, CSS, JS, PNG, JPG, GIF, SVG, WOFF, TTF, JSON, XML, PDF, etc."
    
    # 6. 特殊处理 index.html 的 Content-Disposition
    - name: Set index.html Content-Disposition
      run: |
        echo "Setting Content-Disposition for index.html..."
        
        # 重新上传 index.html，在保持公有读权限的同时添加 Content-Disposition
        coscmd upload -f -H "{'x-cos-acl':'public-read','Content-Disposition':'inline','Content-Type':'text/html'}" index.html /index.html
        
        echo "✅ index.html Content-Disposition set to inline"
    
    # 7. 验证上传结果
    - name: Verify upload
      run: |
        echo "Verifying uploaded files..."
        coscmd list -ar
        
        echo "Checking index.html info..."
        coscmd info index.html || echo "Could not get index.html info"
        
        echo "Upload verification completed"
    
    # 8. 备用权限设置（如果上述方法不生效）
    - name: Backup permission setting
      continue-on-error: true
      run: |
        echo "Setting backup permissions for all uploaded files..."
        
        # 获取所有上传的文件列表，为每个文件设置权限
        coscmd list -ar | grep -v "^Directory" | awk '{print $NF}' | while read file; do
          if [ -n "$file" ] && [ "$file" != "." ]; then
            echo "Setting permissions for: $file"
            coscmd putobjectacl --grant-read "*" "$file" || echo "Failed to set permissions for $file"
          fi
        done
    
    # 9. 部署成功
    - name: Deploy Success
      run: |
        echo "🎉 部署成功!"
        echo ""
        echo "📁 上传的文件："
        coscmd list -ar | head -20
        echo ""
        echo "🌐 网站地址: https://${{ secrets.COS_BUCKET }}.cos-website.${{ secrets.COS_REGION }}.myqcloud.com"
        echo ""
        echo "✅ 所有文件已设置为公有读私有写权限"
        echo "✅ index.html 已设置 Content-Disposition: inline"
        echo "✅ 支持所有静态网站文件类型"
