name: Deploy to Tencent COS
# 当推送到 main 分支时触发
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1. 检出代码
    - name: Checkout
      uses: actions/checkout@v4
    
    # 2. 安装和配置 coscmd 工具
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install coscmd
      run: |
        pip install coscmd
    
    # 3. 配置 coscmd
    - name: Configure coscmd
      run: |
        coscmd config -a ${{ secrets.TENCENT_SECRET_ID }} \
                     -s ${{ secrets.TENCENT_SECRET_KEY }} \
                     -b ${{ secrets.COS_BUCKET }} \
                     -r ${{ secrets.COS_REGION }}
    
    # 4. 准备要上传的文件
    - name: Prepare files for upload
      run: |
        # 创建临时目录，只复制需要的文件
        mkdir -p ./deploy-temp
        
        # 复制网站文件
        cp index.html ./deploy-temp/ 2>/dev/null || true
        cp -r css ./deploy-temp/ 2>/dev/null || true
        cp -r js ./deploy-temp/ 2>/dev/null || true
        cp -r images ./deploy-temp/ 2>/dev/null || true
        cp -r assets ./deploy-temp/ 2>/dev/null || true
        
        # 显示要上传的文件
        echo "Files to upload:"
        find ./deploy-temp -type f
    
    # 5. 设置存储桶权限
    - name: Set bucket permissions
      run: |
        # 设置存储桶为公有读私有写
        echo "Setting bucket to public-read..."
        coscmd putbucketacl --grant-read uri=http://cam.qcloud.com/groups/global/AllUsers
        echo "Bucket permissions set successfully!"
    
    # 6. 同步文件到 COS
    - name: Upload to COS
      run: |
        # 上传准备好的文件到 COS，自动确认删除
        cd deploy-temp
        echo "y" | coscmd upload -r -s --delete ./ /
        
        # 设置 index.html 的正确权限
        coscmd putobjectacl --grant-read "*" index.html || true
    
    # 7. 设置文件的正确 Headers
    - name: Set file headers
      run: |
        # 为 HTML 文件设置正确的权限
        coscmd putobjectacl --grant-read "*" index.html || true
        
        # 为其他文件设置权限
        find ./deploy-temp -name "*.html" -type f | while read file; do
          filename=$(basename "$file")
          echo "Setting permissions for $filename"
          coscmd putobjectacl --grant-read "*" "$filename" || true
        done
    
    # 8. 确认存储桶权限
    - name: Verify bucket permissions
      run: |
        echo "Verifying bucket permissions..."
        coscmd getbucketacl || true
        echo "Deployment completed!"
    
    # 9. 清理临时文件
    - name: Cleanup
      run: |
        rm -rf ./deploy-temp
    
    # 10. 输出部署结果
    - name: Deploy Success
      run: |
        echo "🎉 部署成功!"
        echo "网站地址: https://${{ secrets.COS_BUCKET }}.cos-website.${{ secrets.COS_REGION }}.myqcloud.com"
